# Generated by Django 4.0.6 on 2022-07-30 17:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.IntegerField(unique=True, validators=[django.core.validators.RegexValidator('[0-9]{11}')]),
        ),
    ]
