# Generated by Django 4.0.6 on 2022-07-25 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_exercise'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exercise',
            new_name='Category',
        ),
    ]
