# Generated by Django 4.0.6 on 2022-07-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='view_profile',
            field=models.BooleanField(default=True),
        ),
    ]
