# Generated by Django 4.0.6 on 2022-07-26 16:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_account_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.IntegerField(unique=True, validators=[django.core.validators.RegexValidator('[9][0-9]{9}')]),
        ),
    ]
