version: '3.9'

services:
        footballclub:
                build: .
                container_name : footballclub
                restart : always
                environment:
                        - POSTGRES_DB=postgres_name
                        - POSTGRES_USER=postgres_user
                        - POSTGRES_PASSWORD=postgres_password
                        - POSTGRES_HOST=postgresql
                depends_on:
                        - postgresql
                ports:
                        - "8000:8000"
                volumes:
                        - .:/footballclub
                networks:
                        - footballclub_network
                        - nginx_network

        postgresql:
                image: postgres:alpine
                container_name : postgresql
                environment:
                        - POSTGRES_DB=postgres_name
                        - POSTGRES_USER=postgres_user
                        - POSTGRES_PASSWORD=postgres_password
                restart : always
                ports:
                        - "5432:5432"
                networks:
                        - footballclub_network
        
        nginx:
                image: nginx:alpine
                container_name: nginx
                restart: always
                ports:
                        - "80:80"
                networks:
                        - nginx_network
                depends_on:
                        - footballclub
                volumes:
                        - ./nginx:/etc/nginx/conf.d
                        - ./static/:/footballclub/static/

networks:
        footballclub_network:
                external: true
        nginx_network:
                external: true